#include <stdio.h>

int sum(int a, int b){
    int c;
    /* Variable a, are initialized at each instance of the sum function.
     * The variable c is local. This meand that it will be created at each instance of the function sum.
     * The variables a,b,c exist only when the function sum is running. */
   
    c = a+b;
    return c;
}

int main(void){
    printf("The sum is: %d\n",sum(8,7));
    
    /* During code execution, before evalute the funciton printf, the function sum must be
     * evaluated. This behaviour can be checked by the file `sum3.s` generated by `gcc sum3.c -S` */
    return 0;
}
